package com.crtc.app;
import android.app.*;import android.os.*;import android.graphics.Color;import android.content.*;import android.database.sqlite.*;import android.database.*;import android.view.*;import android.widget.*;import java.util.*;
/** Native Android entry point. No WebView or Trusted Web Activity is used. */
public final class MainActivity extends Activity {
 LinearLayout body; EventStore events; InventoryStore inventory; final int gold=Color.rgb(212,175,55);
 public void onCreate(Bundle b){super.onCreate(b);events=new EventStore(this);inventory=new InventoryStore(this);analyze();}
 void base(String title,String help){ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.rgb(9,11,18));body=new LinearLayout(this);body.setPadding(32,28,32,28);body.setOrientation(LinearLayout.VERTICAL);s.addView(body);setContentView(s);add(title,30,gold);add(help,15,Color.LTGRAY);LinearLayout n=new LinearLayout(this);for(String x:new String[]{"Analyze","Inventory","Cross-list","Plans","Settings"}){Button b=new Button(this);b.setText(x);b.setOnClickListener(v->{if(x.equals("Analyze"))analyze();else if(x.equals("Inventory"))inventory();else if(x.equals("Cross-list"))cross(null);else if(x.equals("Plans"))plans();else settings();});n.addView(b,new LinearLayout.LayoutParams(0,58,1));}body.addView(n);events.record("screen_view","screen="+title);}
 void add(String x,float size,int c){TextView v=new TextView(this);v.setText(x);v.setTextSize(size);v.setTextColor(c);v.setPadding(5,7,5,12);body.addView(v);} LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setPadding(22,18,22,18);c.setOrientation(LinearLayout.VERTICAL);c.setBackgroundColor(Color.rgb(25,29,42));body.addView(c);return c;} EditText input(String h,String v){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.GRAY);return e;} Button go(String x){Button b=new Button(this);b.setText(x);b.setTextColor(Color.BLACK);b.setBackgroundColor(gold);return b;} double num(EditText e){try{double x=Double.parseDouble(e.getText().toString());return x>=0&&Double.isFinite(x)?x:0;}catch(Exception z){return 0;}} String money(double x){return String.format(Locale.US,"$%,.2f",x);}
 void analyze(){base("Analyze a deal","Enter what you can buy it for and what you expect to sell it for.");LinearLayout c=card();EditText cost=input("Purchase / hammer price","0"),resale=input("Expected resale price","0"),fee=input("Resale fee %","13"),premium=input("Buyer premium %","18");for(EditText e:new EditText[]{cost,resale,fee,premium})c.addView(e);TextView out=new TextView(this);out.setTextSize(18);out.setTextColor(Color.WHITE);c.addView(out);Button b=go("ANALYZE DEAL");b.setOnClickListener(v->{Deal d=Deal.calc(num(cost),num(resale),num(fee),num(premium));out.setText(d.verdict+"\nProfit: "+money(d.profit)+" • ROI: "+(Double.isInfinite(d.roi)?"∞":String.format("%.1f%%",d.roi))+"\nTrue cost "+money(d.cost)+" • Net resale "+money(d.net));events.record("deal_analyzed","cost="+cost.getText()+"|resale="+resale.getText()+"|verdict="+d.verdict+"|roi="+d.roi);});c.addView(b);add("In memory of my father, Christopher Hale, who tracked trucks in C++ before I ever tracked a deal.",12,Color.rgb(151,137,97));}
 void inventory(){base("Inventory","Save items here after you decide to buy. Tap an item to draft an eBay Sandbox listing.");LinearLayout c=card();EditText name=input("Item name",""),cost=input("Cost basis","0"),price=input("List price","0");c.addView(name);c.addView(cost);c.addView(price);Button b=go("SAVE ITEM");b.setOnClickListener(v->{inventory.add(name.getText().toString().isEmpty()?"Untitled":name.getText().toString(),num(cost),num(price));inventory();});c.addView(b);for(Item i:inventory.all()){TextView t=new TextView(this);t.setText(i.name+"\nCost "+money(i.cost)+" • List "+money(i.price));t.setTextColor(Color.WHITE);t.setTextSize(16);t.setPadding(15,15,15,15);t.setOnClickListener(v->cross(i));body.addView(t);}}
 void cross(Item i){base("eBay sandbox cross-list","Save a local draft, then publish only when Sandbox credentials and policies are configured.");LinearLayout c=card();EditText title=input("Listing title",i==null?"":i.name),price=input("Price",i==null?"0":String.valueOf(i.price));c.addView(title);c.addView(price);TextView status=new TextView(this);status.setTextColor(Color.LTGRAY);c.addView(status);Button d=go("SAVE SANDBOX DRAFT");d.setOnClickListener(v->{events.record("ebay_draft","title="+title.getText()+"|price="+price.getText());status.setText("Draft saved locally. Review it, then publish to eBay Sandbox.");});c.addView(d);Button p=go("PUBLISH TO SANDBOX");p.setOnClickListener(v->{status.setText("Sandbox-only publish is blocked until the user token, location, and policies from ebay_sell.py are configured. No production endpoint exists in this app.");events.record("ebay_publish","result=configuration_needed");});c.addView(p);}
 void plans(){base("Choose a plan","Subscriptions unlock monthly analysis limits. Free requires verified email.");LinearLayout c=card();for(String x:new String[]{"Free — $0 • 5 analyses/month","Starter — $25 • 50 analyses","Pro • Most Popular — $50 • 250 analyses","Business — $100 • 1,000 analyses, 3 seats","Enterprise — $200 • 5,000 analyses, 10 seats"}){Button b=go(x);b.setOnClickListener(v->Toast.makeText(this,"Register this subscription in Play Console to enable billing test purchases.",Toast.LENGTH_LONG).show());c.addView(b);}}
 void settings(){base("Settings & privacy","Holy Grail thresholds are editable. The app requests only Internet access.");LinearLayout c=card();EditText roi=input("Holy Grail minimum ROI %","40"),profit=input("Minimum profit $","15"),max=input("Maximum buy cost $","100"),fee=input("Default resale fee %","13"),premium=input("Default buyer premium %","18");for(EditText e:new EditText[]{roi,profit,max,fee,premium})c.addView(e);Button b=go("SAVE SETTINGS");b.setOnClickListener(v->{getPreferences(0).edit().putString("holy_grail","roi="+roi.getText()+"|profit="+profit.getText()+"|max="+max.getText()+"|fee="+fee.getText()+"|premium="+premium.getText()).apply();Toast.makeText(this,"Settings saved",Toast.LENGTH_SHORT).show();});c.addView(b);add("Privacy: Appraze stores deal inputs, verdicts, screen views, and publishing outcomes on this device as structured usage events. This build does not share ad data. Usage-data collection is disclosed here.",14,Color.LTGRAY);}
}
class Deal{double cost,net,profit,roi;String verdict;static Deal calc(double cost,double resale,double fee,double premium){Deal d=new Deal();d.cost=cost*(1+premium/100);d.net=resale*(1-fee/100);d.profit=d.net-d.cost;d.roi=d.cost>0?d.profit/d.cost*100:d.profit>0?Double.POSITIVE_INFINITY:0;d.verdict=d.roi>=60?"STRONG BUY":d.roi>=40?"BUY":d.roi>=20?"AT CEILING":d.roi>=5?"BORDERLINE":"PASS";return d;}}
class Item{String name;double cost,price;Item(String n,double c,double p){name=n;cost=c;price=p;}} class EventStore extends SQLiteOpenHelper{EventStore(Context x){super(x,"events.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE events(type TEXT,payload TEXT,created_at INTEGER)");}public void onUpgrade(SQLiteDatabase d,int a,int b){}void record(String t,String p){ContentValues v=new ContentValues();v.put("type",t);v.put("payload",p);v.put("created_at",System.currentTimeMillis());getWritableDatabase().insert("events",null,v);}} class InventoryStore extends SQLiteOpenHelper{InventoryStore(Context x){super(x,"inventory.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE inventory(name TEXT,cost REAL,price REAL)");}public void onUpgrade(SQLiteDatabase d,int a,int b){}void add(String n,double co,double pr){ContentValues v=new ContentValues();v.put("name",n);v.put("cost",co);v.put("price",pr);getWritableDatabase().insert("inventory",null,v);}ArrayList<Item>all(){ArrayList<Item>x=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT name,cost,price FROM inventory ORDER BY rowid DESC",null);while(c.moveToNext())x.add(new Item(c.getString(0),c.getDouble(1),c.getDouble(2)));c.close();return x;}}
